sudo: true
language: node_js
cache:
  yarn: true
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
  - node_modules
notifications:
  email: false
node_js:
  - 8
env:
  - TASK=lint
  - TASK=coverage
before_install:
  - npm install -g npm codecov greenkeeper-lockfile@1
before_script:
  - npx testrpc > /dev/null & 
  - sleep 5
  - greenkeeper-lockfile-update
after_script: 
  - greenkeeper-lockfile-upload
  - npm run coverage && cat coverage/lcov.info | coveralls
script:
  - "npm run $TASK"